white_lower_h: 0
white_lower_s: 0
white_lower_v: 150
white_upper_h: 180
white_upper_s: 60
white_upper_v: 255
yellow_lower_h: 15
yellow_lower_s: 80
yellow_lower_v: 80
yellow_upper_h: 45
yellow_upper_s: 255
yellow_upper_v: 255
